export const getMockData = () => {
  const data = [
    {
      'id': '1',
      'firstName': 'Kate',
      'lastName': 'Blonde',
      'job': ['Counselor'],
      'workAt': ['counseling-master'],
      'age': 25,
      'group': ['general meeting'],
      'image': 'https://firebasestorage.googleapis.com/v0/b/yudai-blog.appspot.com/o/anime%2Foregairu.jpeg?alt=media&token=f4ebcd74-668b-4695-b143-100a9ee54eb9',
      'facebook': null,
      'linkedIn': null,
      'phoneNumber': 36823890293480923,
      'gender': 'female',
      'note': 'met at a counseling place',
      'registeredTime': 1636174915,
      'hobby': ['talking', 'travelling'],
      'city': 'Fremont'
    },
    {
      'id': '2',
      'firstName': 'Kate',
      'lastName': 'Blonde',
      'job': ['Counselor'],
      'workAt': ['counseling-master'],
      'age': 25,
      'group': ['general meeting'],
      'image': 'https://firebasestorage.googleapis.com/v0/b/yudai-blog.appspot.com/o/anime%2Foregairu.jpeg?alt=media&token=f4ebcd74-668b-4695-b143-100a9ee54eb9',
      'facebook': null,
      'linkedIn': null,
      'phoneNumber': 36823890293480923,
      'gender': 'female',
      'note': 'met at a counseling place',
      'registeredTime': 1636174915,
      'hobby': ['talking', 'travelling'],
      'city': 'Fremont'
    },
    {
      'id': '3',
      'firstName': 'Kate',
      'lastName': 'Blonde',
      'job': ['Counselor'],
      'workAt': ['counseling-master'],
      'age': 25,
      'group': ['general meeting'],
      'image': 'https://firebasestorage.googleapis.com/v0/b/yudai-blog.appspot.com/o/anime%2Foregairu.jpeg?alt=media&token=f4ebcd74-668b-4695-b143-100a9ee54eb9',
      'facebook': null,
      'linkedIn': null,
      'phoneNumber': 36823890293480923,
      'gender': 'female',
      'note': 'met at a counseling place',
      'registeredTime': 1636174915,
      'hobby': ['talking', 'travelling'],
      'city': 'Fremont'
    },
    {
      'id': '4',
      'firstName': 'Kate',
      'lastName': 'Blonde',
      'job': ['Counselor'],
      'workAt': ['counseling-master'],
      'age': 25,
      'group': ['general meeting'],
      'image': 'https://firebasestorage.googleapis.com/v0/b/yudai-blog.appspot.com/o/anime%2Foregairu.jpeg?alt=media&token=f4ebcd74-668b-4695-b143-100a9ee54eb9',
      'facebook': null,
      'linkedIn': null,
      'phoneNumber': 36823890293480923,
      'gender': 'female',
      'note': 'met at a counseling place',
      'registeredTime': 1636174915,
      'hobby': ['talking', 'travelling'],
      'city': 'Fremont'
    },
    {
      'id': '5',
      'firstName': 'Kate',
      'lastName': 'Blonde',
      'job': ['Counselor'],
      'workAt': ['counseling-master'],
      'age': 25,
      'group': ['general meeting'],
      'image': 'https://firebasestorage.googleapis.com/v0/b/yudai-blog.appspot.com/o/anime%2Foregairu.jpeg?alt=media&token=f4ebcd74-668b-4695-b143-100a9ee54eb9',
      'facebook': null,
      'linkedIn': null,
      'phoneNumber': 36823890293480923,
      'gender': 'female',
      'note': 'met at a counseling place',
      'registeredTime': 1636174915,
      'hobby': ['talking', 'travelling'],
      'city': 'Fremont'
    },
  ];

  return data;
};